/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface DisplayFeed {
        "filter": string|"latest"|"popular";
        "icon": string;
        "iconColor": string;
        "type": string;
    }
    interface MidwestDocs {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLDisplayFeedElement extends Components.DisplayFeed, HTMLStencilElement {
    }
    var HTMLDisplayFeedElement: {
        prototype: HTMLDisplayFeedElement;
        new (): HTMLDisplayFeedElement;
    };
    interface HTMLMidwestDocsElement extends Components.MidwestDocs, HTMLStencilElement {
    }
    var HTMLMidwestDocsElement: {
        prototype: HTMLMidwestDocsElement;
        new (): HTMLMidwestDocsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "display-feed": HTMLDisplayFeedElement;
        "midwest-docs": HTMLMidwestDocsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface DisplayFeed {
        "filter"?: string|"latest"|"popular";
        "icon"?: string;
        "iconColor"?: string;
        "type"?: string;
    }
    interface MidwestDocs {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "display-feed": DisplayFeed;
        "midwest-docs": MidwestDocs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "display-feed": LocalJSX.DisplayFeed & JSXBase.HTMLAttributes<HTMLDisplayFeedElement>;
            "midwest-docs": LocalJSX.MidwestDocs & JSXBase.HTMLAttributes<HTMLMidwestDocsElement>;
        }
    }
}
