/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MidwestAvatar {
        "color": string;
        "dark": boolean;
        "icon": string;
        "initials": string;
        "name": string;
        "noTooltip": boolean;
        "processing": boolean;
        "shape": "circle" | "square" | "rectangle" | "diamond" | "hexagon" | "star" | "message";
        "size": "tiny" | "small" | "medium-small" | "medium" | "large" | "xlarge" | "huge";
        "src": string;
    }
}
declare global {
    interface HTMLMidwestAvatarElement extends Components.MidwestAvatar, HTMLStencilElement {
    }
    var HTMLMidwestAvatarElement: {
        prototype: HTMLMidwestAvatarElement;
        new (): HTMLMidwestAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "midwest-avatar": HTMLMidwestAvatarElement;
    }
}
declare namespace LocalJSX {
    interface MidwestAvatar {
        "color"?: string;
        "dark"?: boolean;
        "icon"?: string;
        "initials"?: string;
        "name"?: string;
        "noTooltip"?: boolean;
        "processing"?: boolean;
        "shape"?: "circle" | "square" | "rectangle" | "diamond" | "hexagon" | "star" | "message";
        "size"?: "tiny" | "small" | "medium-small" | "medium" | "large" | "xlarge" | "huge";
        "src"?: string;
    }
    interface IntrinsicElements {
        "midwest-avatar": MidwestAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "midwest-avatar": LocalJSX.MidwestAvatar & JSXBase.HTMLAttributes<HTMLMidwestAvatarElement>;
        }
    }
}
