/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MidwestDevice {
        /**
          * The Device Name
         */
        "frame": "apple-tv"|"apple-tv-in-app"|"apple-watch-42-black"|"apple-watch-42-white"|"apple-watch-44-black"|"apple-watch-44-white"|"imac-pro"|"imac"|"ipad-pro-portrait"|"ipad-pro-landscape"|"iphone-8-silver"|"iphone-8-spacegray"|"iphone-8-plus-silver"|"iphone-8-plus-spacegray"|"iphone-xs"|"iphone-xs-max"|"ipod-touch-portrait-blue"|"ipod-touch-landscape-blue"|"ipod-touch-portrait-silver"|"ipod-touch-landscape-silver"|"macbook-air"|"macbook-pro";
        "retina": boolean;
    }
}
declare global {
    interface HTMLMidwestDeviceElement extends Components.MidwestDevice, HTMLStencilElement {
    }
    var HTMLMidwestDeviceElement: {
        prototype: HTMLMidwestDeviceElement;
        new (): HTMLMidwestDeviceElement;
    };
    interface HTMLElementTagNameMap {
        "midwest-device": HTMLMidwestDeviceElement;
    }
}
declare namespace LocalJSX {
    interface MidwestDevice {
        /**
          * The Device Name
         */
        "frame"?: "apple-tv"|"apple-tv-in-app"|"apple-watch-42-black"|"apple-watch-42-white"|"apple-watch-44-black"|"apple-watch-44-white"|"imac-pro"|"imac"|"ipad-pro-portrait"|"ipad-pro-landscape"|"iphone-8-silver"|"iphone-8-spacegray"|"iphone-8-plus-silver"|"iphone-8-plus-spacegray"|"iphone-xs"|"iphone-xs-max"|"ipod-touch-portrait-blue"|"ipod-touch-landscape-blue"|"ipod-touch-portrait-silver"|"ipod-touch-landscape-silver"|"macbook-air"|"macbook-pro";
        "retina"?: boolean;
    }
    interface IntrinsicElements {
        "midwest-device": MidwestDevice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "midwest-device": LocalJSX.MidwestDevice & JSXBase.HTMLAttributes<HTMLMidwestDeviceElement>;
        }
    }
}
