/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MidwestPjax {
        "loadContent": (body: any) => Promise<any>;
        "loadUrl": (url: any) => Promise<any>;
        "pjax": any;
        "replace": (selector: any, url: any) => Promise<void>;
    }
}
declare global {
    interface HTMLMidwestPjaxElement extends Components.MidwestPjax, HTMLStencilElement {
    }
    var HTMLMidwestPjaxElement: {
        prototype: HTMLMidwestPjaxElement;
        new (): HTMLMidwestPjaxElement;
    };
    interface HTMLElementTagNameMap {
        "midwest-pjax": HTMLMidwestPjaxElement;
    }
}
declare namespace LocalJSX {
    interface MidwestPjax {
        "pjax"?: any;
    }
    interface IntrinsicElements {
        "midwest-pjax": MidwestPjax;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "midwest-pjax": LocalJSX.MidwestPjax & JSXBase.HTMLAttributes<HTMLMidwestPjaxElement>;
        }
    }
}
